service:
  name: auction-service

plugins:
  - serverless-bundle
  - serverless-pseudo-parameters

provider:
  name: aws
  runtime: nodejs12.x
  memorySize: 256
  stage: ${opt:stage, 'dev'}
  region: us-west-1
  iamRoleStatements: 
    - ${file(iam/AuctionsTableIAM.yml):AuctionsTableIAM}
    
resources:
  Resources:
    AuctionsTable: ${file(resources/AuctionTable.yml):AuctionsTable}

functions:
  createAuction:
    handler: src/handlers/createAuction.handler
    events:
      - http:
          method: POST
          path: /createAuction

custom:
  bundle:
    linting:false
